Text ::= ([^\{] | '{{' | '}}')+
Name ::= [0-9A-z_]+
Index::= [0-9]+
Format ::= [^\{]+
Template ::= (Text | Hole)*
Hole ::=  '{' ('@' | '$')? (Name | Index) (',' Alignment)? (':' Format)? '}'
Alignment ::= '-'?[0-9]+
